### ISSUE TITLE
Sources Page

### ISSUE THREAD

**Issue by sarvesh4396** [sarvesh4396/freeresourceshub#1]
A page to show all sources in like the way resources are shown and one can go to that website directly.

Include a sources page in the navbar of the site with name sources.
The sources page will show all sources in a grid.
A user can go to the official source site by clicking on it.

All the sources can be accessed using this [file](https://github.com/sarvesh4396/freeresourceshub/blob/master/src/assets/data/sources.json)

**Comment by avezqureshi14** [comment]
@sarvesh4396  I like to contribute to this issue but please can you explain me this in more clear way

**Comment by sarvesh4396** [comment]
hey @avezqureshi14, I have updated the comment.
If still you face any issues let me know.
