### ISSUE TITLE
A form page

### ISSUE THREAD

**Issue by sarvesh4396** [sarvesh4396/freeresourceshub#2]
A form page from where users can submit a source or resource easily.
The form should include:-
- Name input text field for the user [**mandatory**]
- User email contact input text field [**optional**]
- Dropdown to select source or resource [**mandatory**]
- Name input text field for source or resource [**mandatory**]
- Source or resource URL input text field [**mandatory**]
- Description text area for source or resource [**mandatory**]

**Comment by janmesh799** [comment]
i think i can do this

**Comment by avezqureshi14** [comment]
@sarvesh4396 can you assign this issue to me

**Comment by sarvesh4396** [comment]
Hi there,

@janmesh799 @avezqureshi14 you both can work on 

> i think i can do this

Go ahead

**Comment by sarvesh4396** [comment]
> @sarvesh4396 can you assign this issue to me

you can still work on this issue but I would suggest working on #1 first.

**Comment by avezqureshi14** [comment]
@sarvesh4396  Sir I just wanted to confirm is this issue assigned to me

**Comment by sarvesh4396** [comment]
> @sarvesh4396 Sir I just wanted to confirm is this issue assigned to me

I have assigned the issue to you and @janmesh799.

**Comment by avezqureshi14** [comment]
> > @sarvesh4396 Sir I just wanted to confirm is this issue assigned to me
> 
> I have assigned the issue to you and @janmesh799.

Ok @sarvesh4396

**Comment by MuhammadJufri** [comment]
Hi @sarvesh4396 
Can you assign this issue to me please

**Comment by sarvesh4396** [comment]
> Hi @sarvesh4396 Can you assign this issue to me please

Sure

**Comment by sarvesh4396** [comment]
Thank you @MuhammadJufri, for your time and contribution.
