### ISSUE TITLE
Add installing and deploying guide

### ISSUE THREAD

**Issue by sarvesh4396** [sarvesh4396/freeresourceshub#6]

**Comment by pandeyom331** [comment]
Assign this to me

**Comment by sarvesh4396** [comment]
> Assign this to me

Assigned

**Comment by pandeyom331** [comment]
Should I add it in existing readme file or a different file for installing and deploying guide ?

**Comment by MuhammadJufri** [comment]
Can you assign this issue to me please

**Comment by sarvesh4396** [comment]
> Should I add it in existing readme file or a different file for installing and deploying guide ?

You can use a different fule and update the link to that file in the README

**Comment by pandeyom331** [comment]
ok

**Comment by sarvesh4396** [comment]
> Can you assign this issue to me please
> 
 Sure,

**Comment by sarvesh4396** [comment]
I will try to merge the first pr for the issue.
